// Jenkins declarative pipeline — v{{VERSION}}
// ------------------------------------------------------------------
// Generated by BMAD DCA Release agent. Stack: {{STACK}}.
// Save this file as `Jenkinsfile` at the repo root.
// ------------------------------------------------------------------
pipeline {
    agent {
        label 'linux-jvm-node'
    }

    // ------------------------------------------------------------------
    // Global tool versions — pin explicitly.
    // ------------------------------------------------------------------
    tools {
        jdk 'jdk-17'
        maven 'maven-3.9'
        nodejs 'node-20'
    }

    parameters {
        string(name: 'RELEASE_VERSION', defaultValue: '{{VERSION}}', description: 'Release version (semver)')
        choice(name: 'TARGET_ENV', choices: ['stage', 'prod'], description: 'Deploy target')
        booleanParam(name: 'SKIP_AUDIT', defaultValue: false, description: 'Skip DCA audit gate (emergency hotfix only)')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '30'))
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
        timestamps()
    }

    environment {
        // Store secrets in Jenkins Credentials; reference by ID.
        DEPLOY_TOKEN = credentials('dca-deploy-token')
    }

    stages {
        // ------------------------------------------------------------------
        stage('Setup') {
            steps {
                echo "Release ${params.RELEASE_VERSION} → ${params.TARGET_ENV}"
                sh 'git fetch --tags --unshallow || true'
            }
        }

        // ------------------------------------------------------------------
        stage('Build') {
            steps {
                sh '''
                    {{BUILD_COMMAND}}
                '''
                // Per-stack: `mvn -B clean install -Padobe-public` (AEM),
                // `./gradlew clean build -x test` (Spring),
                // `composer install --no-dev && bin/magento setup:di:compile` (Commerce PaaS).
            }
            post {
                success {
                    archiveArtifacts artifacts: '{{BUILD_ARTIFACT_PATH}}', allowEmptyArchive: false
                }
            }
        }

        // ------------------------------------------------------------------
        stage('Test') {
            steps {
                sh '''
                    {{TEST_COMMAND}}
                '''
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml,**/junit.xml'
                    publishHTML(target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: '{{COVERAGE_REPORT_DIR}}',
                        reportFiles: 'index.html',
                        reportName: 'Coverage'
                    ])
                }
            }
        }

        // ------------------------------------------------------------------
        stage('Security Scan') {
            steps {
                // DCA sonar-scan agent — LLM-driven quality + vuln scan.
                sh '''
                    npx ts-node .claude/skills/bmad-dept-code-sonar-scan-agent/scripts/run.ts \\
                      --path . \\
                      --engine {{ENGINE}} \\
                      --technical \\
                      --no-preflight \\
                      --yes-install \\
                      --fail-on-overdue
                '''
            }
        }

        // ------------------------------------------------------------------
        stage('Audit Gate') {
            when { expression { return !params.SKIP_AUDIT } }
            steps {
                // DCA audit agent — pre-release gate.
                sh '''
                    npx ts-node .claude/skills/bmad-dept-code-audit-agent/scripts/run.ts \\
                      --path . \\
                      --engine {{ENGINE}} \\
                      --technical \\
                      --no-preflight \\
                      --yes-install \\
                      --fail-on-overdue
                '''
                // DCA test-coverage floor gate.
                sh '''
                    npx ts-node .claude/skills/bmad-dept-code-test-coverage-agent/scripts/run.ts \\
                      --path . \\
                      --engine {{ENGINE}} \\
                      --mode analyze \\
                      --technical \\
                      --no-preflight \\
                      --yes-install
                '''
            }
        }

        // ------------------------------------------------------------------
        stage('Deploy Stage') {
            steps {
                withCredentials([string(credentialsId: 'dca-deploy-token', variable: 'DEPLOY_TOKEN')]) {
                    sh '''
                        {{DEPLOY_COMMAND}}
                    '''
                    // Per-stack: `mvn deploy` (Sling / Spring),
                    // `aio app deploy --workspace stage` (App Builder),
                    // `bin/magento setup:upgrade && bin/magento cache:flush` (Commerce PaaS).
                }
            }
        }

        // ------------------------------------------------------------------
        stage('Approve Prod') {
            when { expression { return params.TARGET_ENV == 'prod' } }
            steps {
                script {
                    def approver = input(
                        message: "Deploy v${params.RELEASE_VERSION} to prod?",
                        ok: 'Deploy',
                        submitterParameter: 'APPROVER',
                        submitter: 'release-approvers,tech-leads'
                    )
                    echo "Prod deploy approved by: ${approver}"
                }
            }
        }

        // ------------------------------------------------------------------
        stage('Deploy Prod') {
            when { expression { return params.TARGET_ENV == 'prod' } }
            steps {
                withCredentials([string(credentialsId: 'dca-deploy-token-prod', variable: 'DEPLOY_TOKEN')]) {
                    sh '''
                        {{DEPLOY_COMMAND}}
                    '''
                }
            }
        }

        // ------------------------------------------------------------------
        stage('Post-Deploy') {
            steps {
                sh '''
                    {{SMOKE_TEST_COMMAND}}
                '''
                echo 'Distribute release-reports/ANNOUNCEMENT.md to Slack/Confluence/email.'
                echo 'Operations agent handles post-deploy alerts + runbook (Phase 3.4).'
            }
        }
    }

    // ------------------------------------------------------------------
    post {
        success {
            echo "Release ${params.RELEASE_VERSION} deployed to ${params.TARGET_ENV}."
            // slackSend, emailext, etc — wire to your notification stack.
        }
        failure {
            echo "Release ${params.RELEASE_VERSION} FAILED. Trigger rollback via Jenkins job 'dca-rollback' with version ${params.RELEASE_VERSION}."
        }
        always {
            archiveArtifacts artifacts: 'release-reports/**/*', allowEmptyArchive: true
        }
    }
}

// ------------------------------------------------------------------
// Stack-specific customization points
// ------------------------------------------------------------------
// 1. Secrets: use Jenkins Credentials (Manage Jenkins → Credentials).
//    Rotate per org SLA. Reference via credentialsId in withCredentials().
// 2. Agent labels: match to your Jenkins node pool. Add `docker` agent
//    for hermetic builds: agent { docker { image 'maven:3.9-eclipse-temurin-17' } }.
// 3. AMS AEM: use the AMS-provided Jenkinsfile template and merge these
//    DCA-agent gate stages into the AMS deploy stages.
// 4. Concurrency: `disableConcurrentBuilds()` serializes per-branch;
//    remove for parallel branch builds.
// 5. Rollback: create a separate Jenkins job 'dca-rollback' parameterized
//    with the target version to redeploy.
