// @ts-check
// Auto-generate the docs sidebar from the folder structure under docs/.
// Category ordering + labels come from each folder's _category_.json.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
